version: "3"

services:
  users:
    container_name: users
    build: ./back/users
    restart: always
    ports:
      - "4000:4000"
    networks:
      - usersnt
    environment:
      - URLDB=mongodb://usersdb:27017/users
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=36000000
      - REFRESH_TOKEN_DURATION=36000000

  usersdb:
    image: mongo:4.0
    restart: always
    networks:
      - usersnt
    ports:
      - "27017:27017"
    volumes:
      - "./mongo/data/users:/data/db"

  classroom:
    container_name: classroom
    build: ./back/classroom
    restart: always
    ports:
      - "4001:4001"
    networks:
      - classroomnt
    environment:
      - URLDB=mongodb://classroomdb:27017/classroom
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=36000000
      - REFRESH_TOKEN_DURATION=36000000

  classroomdb:
    image: mongo:4.0
    restart: always
    networks:
      - classroomnt
    volumes:
      - "./mongo/data/classroom:/data/db"

  grade:
    container_name: grade
    build: ./back/grade
    restart: always
    ports:
      - "4002:4002"
    networks:
      - gradent
    environment:
      - URLDB=mongodb://gradedb:27017/grade
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=36000000
      - REFRESH_TOKEN_DURATION=36000000

  gradedb:
    image: mongo:4.0
    restart: always
    networks:
      - gradent
    volumes:
      - "./mongo/data/grade:/data/db"

networks:
  usersnt:
  gradent:
  classroomnt:
