version: "3"

services:
  users:
    container_name: users
    build: ./back/users
    restart: always
    ports:
     - "4000:4000"
    links:
      - usersdb
    environment:
      - URLDB=mongodb://usersdb:27017/users
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=3600000
      - REFRESH_TOKEN_DURATION=36000000

  usersdb:
    image: mongo:4.0
    restart: always
    volumes:
      - "./mongo/data:/data/users"

  classroom:
    container_name: classroom
    build: ./back/classroom
    restart: always
    ports:
     - "4001:4001"
    links:
      - classroomdb
    environment:
      - URLDB=mongodb://classroomdb:27017/classroom
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=3600000
      - REFRESH_TOKEN_DURATION=36000000

  classroomdb:
    image: mongo:4.0
    restart: always
    volumes:
      - "./mongo/data:/data/classroom"

  grade:
    container_name: grade
    build: ./back/grade
    restart: always
    ports:
     - "4002:4002"
    links:
      - gradedb
    environment:
      - URLDB=mongodb://gradedb:27017/grade
      - ACCESS_TOKEN_SECRET="secret"
      - REFRESH_TOKEN_SECRET="secret"
      - ACCESS_TOKEN_DURATION=3600000
      - REFRESH_TOKEN_DURATION=36000000

  gradedb:
    image: mongo:4.0
    restart: always
    volumes:
      - "./mongo/data:/data/grade"